language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
  - npm install pubnub
  - npm install johnny-five
install:
  - npm install
script:
  - npm test
  - npm run build
on:
  branch: master
